# Generated by Django 3.0.8 on 2020-07-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='unit',
            field=models.IntegerField(null=True),
        ),
    ]
