# Generated by Django 3.0.8 on 2020-07-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0002_course_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
