# Generated by Django 3.0.8 on 2020-07-29 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stud', '0003_course_course_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('level',)},
        ),
        migrations.CreateModel(
            name='Level_CGPA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_semester_gp', models.IntegerField()),
                ('second_semester_gp', models.IntegerField()),
                ('cgpa', models.FloatField()),
                ('overall_cgpa', models.FloatField()),
                ('level', models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level'), ('600', '600 Level')], max_length=4)),
                ('first_semester_unit', models.IntegerField()),
                ('second_semester_unit', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
